# Generated by Django 4.2.30 on 2026-05-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_author_article_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authorId',
            new_name='author',
        ),
    ]
