# Generated by Django 4.2.30 on 2026-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlecomment_author_savedarticle_commentreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
